# From https://github.com/wjh720/QPLEX/
# --- Qatten specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000

runner: "parallel"
batch_size_run: 8
buffer_size: 5000
batch_size: 128


# update the target network every {} episodes
target_update_interval: 200
t_max: 10050000
save_model: False # Save the models to disk

mac: "gmof_mac"
agent: "gmof"
# use the Q_Learner to train
agent_output_type: "q"
learner: "mamf_momf_learner"
double_q: True
mixer: "mamf_momf"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 2
adv_hypernet_embed: 64
td_lambda: 0.6
lr: 0.0005
grad_norm_clip: 5 # Reduce magnitude of gradients above this L2 norm

num_kernel: 4
is_minus_one: True
weighted_head: True
is_adv_attention: True
is_stop_gradient: True

name: "momqplex_t_s_10_11_test"
